original:
  _target_: src.our_datasets.BoolQOriginalDataset
  _partial_: True
  columns: [passage, question]
generated:
  _target_: src.our_datasets.BoolQGeneratedDataset
  _partial_: True
  columns: [passage, question]
  label_col: "answer"
