common_config:
  header: "Given a passage and a question generate 1 if the question is correct based
  on the passage of 0 if it in incorrect."
  footer: "Answer: "
  columns:
    passage: "Passage: "
    question: "Question: "
original:
  _target_: src.our_datasets.Dataset
generated:
  _target_: src.our_datasets.BoolQGeneratedDataset
  label_col: "answer"
