original:
  _target_: src.our_datasets.Dataset
  _partial_: True
  columns: [passage, question]
generated:
  _target_: src.our_datasets.BoolQGeneratedDataset
  _partial_: True
  columns: [passage, question]
