original:
  _target_: our_datasets.CopaOriginalDataset
  _partial_: True
  columns: [sentence1, sentence2, word]
generated:
  _target_: our_datasets.CopaOriginalDataset
  _partial_: True
  columns: [sentence1, sentence2, word]
