common_config:
  header: "Given a premise and hypothesis, generate 0 if the premise
  entails the hypothesis. Generate 1 if the premise does not entail the
  hypothesis."
  footer: "Answer: "
  columns:
    premise: "Premise: "
    hypothesis: "Hypothesis: "
original:
  _target_: src.our_datasets.Dataset
generated:
  _target_: src.our_datasets.RteGeneratedDataset
