original:
  _target_: src.our_datasets.WicOriginalDataset
  _partial_: True
  columns: [sentence1, sentence2, word]
generated:
  _target_: src.our_datasets.WicGeneratedDataset
  _partial_: True
  columns: [sentence1, sentence2, word]
