original:
  _target_: our_datasets.Dataset
  _partial_: True
  columns: [sentence1, sentence2, word]
generated:
  _target_: our_datasets.WicGeneratedDataset
  _partial_: True
  columns: [sentence1, sentence2, word]
