metric: 
  _target_: "src.our_metrics.compute_f1_metrics"
prediction_metric:
  _target_: "src.our_metrics.compute_f1_prediction_metrics"

cache_dir: "./.cache"

save_strategy: "epoch"
logging_strategy: "epoch"
evaluation_strategy: "epoch"

text_column: "text"
label_column: "label"

save_total_limit: 1          # Save a max of 1 epoch
preprocessing_num_workers: 4

metric_for_best_model: "accuracy"
load_best_model_at_end: True # Load the best model at the end of training

seed: 42
per_device_eval_batch_size: 32
per_device_train_batch_size: 8

optim: "adamw_torch"
warmup_ratio: .20
learning_rate: .00001 # 1e-5
num_train_epochs: 100

early_stopping_patience: 25
early_stopping_threshold: 0.001

do_train: True
do_eval: True
do_predict: True
predict_with_generate: True
