defaults:
  - outputs
  - experiment_defaults
  - preprocessing_config: record
  - _self_
hydra:
  env:
    save_name: "${hydra:env.dataset_name}_${hydra:env.model_name}"

model_name: "bert-base-cased"
dataset_name: "record"

train_files:
  - "datasets/${hydra:env.dataset_name}/gpt3_generated.json"

output_dir: "models/${hydra:env.dataset_name}/${hydra:env.model_name}"

num_labels: 2
num_samples: 1228
batch_tokenization: True

metric_for_best_model: "raw_accuracy"
metric:
  _target_: "src.our_metrics.compute_record_f1_metrics"
prediction_metric:
  _target_: "src.our_metrics.compute_record_f1_prediction_metrics"
